esphome:
  name: esp32-tempsensor
  friendly_name: ESP32-TempSensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "AUTO_GENERATED_KEY="

ota:
  password: "MAGIC_PASSWORD_APPEARING_HERE"

sensor:
  - platform: dht
    pin: GPIO27
    model: DHT22
    update_interval: 30s
    temperature:
      name: "DHT22 Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    humidity:
      name: "DHT22 Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Tempsensor"
    password: "PASSWORD_TO_THE_IP_HERE"
  manual_ip:
    static_ip: 192.168.0.152
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 

captive_portal: